In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


In [4]:
## Introduction to Tensors

### Creating tensors 

In [5]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
# Everything in Pytorch works off of 'torch.tensor()'

In [7]:
scalar.ndim

0

In [8]:
# Get tensor back as Python int
scalar.item()

7

In [9]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim


1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[0]

tensor([7, 8])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])


In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape
# one, 3x3 shape tensor

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [23]:
TENSOR[2]

IndexError: ignored

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with the tensors full of random numbers and then adjust those random numbers to better represent the data 

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [24]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
# google torch.rand and read the documentation
random_tensor

tensor([[0.0577, 0.7198, 0.3286, 0.4367],
        [0.3338, 0.9100, 0.6656, 0.2186],
        [0.6927, 0.7091, 0.4282, 0.5346]])

In [25]:
random_tensor.ndim

2

In [26]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R,G,B) ... colour channels can also be (3, 224, 224)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [27]:
# neural networks start with random numbers ... most of this is done in the background

In [30]:
custom_tensor = torch.rand(1,5,5)
custom_tensor.shape, custom_tensor.ndim

(torch.Size([1, 5, 5]), 3)

In [31]:
torch.rand(size=(3,3))

tensor([[0.0415, 0.4929, 0.5865],
        [0.6150, 0.5482, 0.1961],
        [0.3806, 0.1340, 0.6932]])

### Zeros and ones

In [33]:
# Create a tensor of all zeros (useful for creating a mask)
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
# all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [37]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [43]:
# Use torch.range()
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Data Types

Note: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:


1.   Tensors not right datatype
2.   Tensors not right shape
3.   Tensors not on the right device



In [51]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,            # what datatype is the tensor (e.g. float32 or float16)
                               device=None,           # what device is your tensor on
                               requires_grad=False)   # whether or not to track gradients with this tensor's operations
float_32_tensor

tensor([3., 6., 9.])

In [50]:
float_32_tensor.dtype

torch.float32

In [52]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [53]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [54]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [55]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [56]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor 

tensor([[0.7329, 0.6559, 0.1035, 0.1133],
        [0.2509, 0.6672, 0.4052, 0.2519],
        [0.7973, 0.3117, 0.8566, 0.1778]])

In [57]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7329, 0.6559, 0.1035, 0.1133],
        [0.2509, 0.6672, 0.4052, 0.2519],
        [0.7973, 0.3117, 0.8566, 0.1778]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [72]:
# Create a tensor that is a float16
# Create a tensor that is on a gpu or cuda
new_tensor = torch.rand(5,5)
new_tensor

tensor([[0.3110, 0.6799, 0.7254, 0.2295, 0.5432],
        [0.5032, 0.6234, 0.8735, 0.3839, 0.7661],
        [0.1736, 0.2028, 0.8336, 0.7737, 0.6518],
        [0.7861, 0.7519, 0.3498, 0.4418, 0.2043],
        [0.0150, 0.5526, 0.4204, 0.6341, 0.7192]])

In [73]:
print(new_tensor)
print(f"Datatype of tensor: {new_tensor.dtype}")
print(f"Shape of tensor: {new_tensor.shape}")
print(f"Device tensor is on: {new_tensor.device}")

tensor([[0.3110, 0.6799, 0.7254, 0.2295, 0.5432],
        [0.5032, 0.6234, 0.8735, 0.3839, 0.7661],
        [0.1736, 0.2028, 0.8336, 0.7737, 0.6518],
        [0.7861, 0.7519, 0.3498, 0.4418, 0.2043],
        [0.0150, 0.5526, 0.4204, 0.6341, 0.7192]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([5, 5])
Device tensor is on: cpu


In [74]:
new_tensor = torch.tensor(new_tensor, dtype= torch.float16)

<ipython-input-74-8d27176c8dea>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  new_tensor = torch.tensor(new_tensor, dtype= torch.float16)


In [75]:
print(new_tensor)
print(f"Datatype of tensor: {new_tensor.dtype}")
print(f"Shape of tensor: {new_tensor.shape}")
print(f"Device tensor is on: {new_tensor.device}")

tensor([[0.3110, 0.6802, 0.7256, 0.2295, 0.5430],
        [0.5034, 0.6235, 0.8735, 0.3838, 0.7661],
        [0.1736, 0.2028, 0.8335, 0.7734, 0.6519],
        [0.7861, 0.7520, 0.3499, 0.4419, 0.2043],
        [0.0150, 0.5527, 0.4204, 0.6343, 0.7192]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([5, 5])
Device tensor is on: cpu


## Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [76]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [77]:
# Multipy tensor by 10
tensor * 10

tensor([10, 20, 30])

In [78]:
tensor

tensor([1, 2, 3])

In [79]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [80]:
# Try out PyTorch built-in functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [81]:
torch.add(tensor,10)

tensor([11, 12, 13])

## Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot-product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html 

There are two main rules that perfomring matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`
* `(8,2) @ (2,6)` -> `(8,6)`

In [92]:
torch.matmul(torch.rand(8,2), torch.rand(2,6))

tensor([[0.2617, 0.6105, 0.1525, 0.7181, 0.2122, 0.6001],
        [0.3748, 0.3854, 0.5130, 0.4827, 0.3841, 0.6703],
        [0.5332, 0.5185, 0.7478, 0.6534, 0.5513, 0.9421],
        [0.4312, 0.6304, 0.4775, 0.7640, 0.4112, 0.8435],
        [0.2279, 0.0980, 0.3940, 0.1412, 0.2559, 0.3548],
        [0.1856, 0.0446, 0.3421, 0.0757, 0.2142, 0.2753],
        [0.4368, 0.6309, 0.4884, 0.7653, 0.4179, 0.8515],
        [0.0402, 0.0722, 0.0364, 0.0862, 0.0361, 0.0838]])

In [84]:
# Element wise mulitplication 
print(tensor, '*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [85]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [86]:
tensor

tensor([1, 2, 3])

In [87]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [89]:
%%time
value = 0 
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 3.32 ms, sys: 0 ns, total: 3.32 ms
Wall time: 8.01 ms


In [90]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 97 µs, sys: 0 ns, total: 97 µs
Wall time: 102 µs


tensor(14)

### One of the most common error in deep learning: shape errors

In [5]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

RuntimeError: ignored

In [6]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [7]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [8]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [9]:
# The matrix multiplication works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")

output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput Shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output Shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [22]:
# create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [12]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [14]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [18]:
# Find the mean ... data type is 'int64' which is 'long'
#torch.mean(x)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [19]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [23]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [24]:
# find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [25]:
x[0]

tensor(1)

In [26]:
# find the position in tensor that has the maximum value
x.argmax()

tensor(9)

In [27]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [29]:
# Let's create a tensor
import torch 
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [30]:
# Add and extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [31]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [32]:
# Changing z changes x (beause a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [33]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [34]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [35]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add and extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [37]:
# torch.permute - rearranges the dimenstions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [44]:
x_original[0, 0, 0] = 69
x_original[0,0,0] , x_permuted[0,0,0]

(tensor(69.), tensor(69.))

In [45]:
#torch.permute - rearranges the dimenstions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")
print(x_original[0,0,0])

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
tensor(0.7600)


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [46]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [47]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [48]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [49]:
x[0,0]

tensor([1, 2, 3])

In [50]:
# Let's index on most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [51]:
x[0,1,2]

tensor(6)

In [58]:
x[0,2,2], x[:,2,2]

(tensor(9), tensor([9]))

In [61]:
x[:,:,2:]

tensor([[[3],
         [6],
         [9]]])

In [53]:
# You can also use ":" to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [55]:
# Get all values of 0th and 1st dimensions but only index 1 of the 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [56]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor (for DL capabilities) --> `torch.from_numpy(ndarray)`
* PyTorch tensor --> NumPy --> `torch.Tensor.numpy()`

In [2]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)#.type(torch.float32) ## warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
print(f"Array Data Type: {array.dtype}")
print(f"Tensor Data Type: {tensor.dtype}")

Array Data Type: float64
Tensor Data Type: torch.float64


In [4]:
# numpy default dtype is float64, whereas torch default is float32
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [5]:
print(f"Array Data Type: {array.dtype}")
print(f"Tensor Data Type: {tensor.dtype}")

Array Data Type: float64
Tensor Data Type: torch.float32


In [6]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [11]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [12]:
# Change the tensor, what happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...

To reduce the randomnes in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

In [13]:
torch.rand(3,3)

tensor([[0.6036, 0.4505, 0.3587],
        [0.5068, 0.1460, 0.4122],
        [0.5450, 0.5858, 0.0819]])

In [14]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8664, 0.5894, 0.8334, 0.6596],
        [0.5744, 0.3284, 0.9225, 0.8403],
        [0.1636, 0.2774, 0.8365, 0.1678]])
tensor([[0.2663, 0.1400, 0.6250, 0.7328],
        [0.4440, 0.7347, 0.7853, 0.7925],
        [0.3492, 0.0658, 0.3771, 0.1726]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [17]:
# Let's make some random but reproducible tensors
import torch
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Different ways of accessing the GPU in Pytorch

Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenese to make everything work well

### 1. Getting a GPU

1. Easiest - Use Google Colab Pro for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation

In [1]:
!nvidia-smi

Wed Mar 29 15:01:32 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P8    12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## 2. Check for GPU access with PyTorch

In [2]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# Count the number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensor/models on the GPU is because using a GPU results in faster computations


In [6]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

#Tensor not on GPU 
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [8]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [10]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [11]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises & Extra Cirriculum